title: Liam Robinson - Portfolio
email: liam.robinson.lmr@gmail.com
description: >-
  Liam Robinson's portfolio, showcasing work from a decade of games development experience.
  Featuring work made with the following technologies amongst others:
    C#, C++, Unity Engine, Unreal Engine, .Net Core
baseurl: ""
url: "oliphan.github.io"
github_username: oliphan

# Build settings
sass:
  style: compressed
  sass_dir: css

assets:
  compress:
    css:  true

exclude:
  - _site/
  - .jekyll-cache/
  - .vscode/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
